#!/usr/bin/env python3
"""CodeAgent 原子壳（open_source:true）。

复用（零改动核心）：dispatch_template 派单5段模板(背景/目标/约束/红线/产出)
只加壳：把既有函数 import 进 run() 包 {ok,data} 信封。

能力域：plan。数据不出厂，可独立运行。
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from atomic_base import AtomicAgent


class CodePlanAgent(AtomicAgent):
    name = "code-plan"
    version = "0.1.0"
    domain = "plan"
    description = "方案设计原子: dispatch_template 5段任务拆解 + gen"
    provides = ["plan.think", "plan.gen"]
    depends_on = ["taskstate.track"]
    inputs = ["task", "language", "domain", "files_needed", "spec"]
    outputs = ["plan", "assumptions", "files_needed", "constraint_chain", "questions", "files", "score"]

    def _register_defaults(self):
        self.register("plan.think", self._think)
        self.register("plan.gen", self._gen)

    # ── plan.think：dispatch_template 派单5段模板任务拆解 ──
    def _think(self, task, language="python", domain="general", files_needed=None):
        """复用派单5段模板把任务拆成可派单方案。纯拼接/启发式，零 LLM。"""
        lang_hint = {"frontend": "响应式布局/组件拆分/状态覆盖",
                     "backend": "API路由/数据流/错误处理/权限",
                     "cli": "参数解析/输出格式化/退出码"}.get(domain, "极简优先·单文件×单增强")
        files = files_needed or self._infer_files(task, language)
        plan = {
            "背景": f"任务: {task}. 领域: {domain}, 语言: {language}.",
            "目标": f"交付 {len(files)} 个文件, 满足 {task}; 目标可证伪(能被测试验证)。",
            "约束": f"技术约束: {lang_hint}; 标准库优先; 复用检索先行; 单文件×单增强。",
            "红线": "不改生产/不删文件/不动系统配置; 敏感数据不出厂。",
            "产出": f"交付文件: {', '.join(files)}; 证据: 测试绿 + 静态分。",
            "files_needed": files,
            "constraint_chain": [f"先满足{task}的主路径", "再补边界值/异常", "最后回归验证"],
            "assumptions": ["目标是明确可测的单一功能", "标准库可用"],
            "questions": [],
            "language": language,
            "domain": domain,
        }
        return plan

    def _infer_files(self, task, language):
        ext = {"python": "main.py", "javascript": "index.js", "go": "main.go"}.get(language, "main.py")
        return [ext]

    # ── plan.gen：按方案产出代码（可透传 code，或从 spec 生成骨架）──
    def _gen(self, task, code=None, spec=None, language="python", files_needed=None):
        """若给 code 则透传(数据不出厂); 否则按 spec 生成真实代码骨架。"""
        if code is not None:
            files = {k: v for k, v in code.items()} if isinstance(code, dict) else {"main.py": code}
            return {"files": files, "score": 100, "source": "provided"}
        files = {}
        names = files_needed or [("main.py" if language == "python" else
                                  "index.js" if language == "javascript" else "main.go")]
        fn = names[0]
        if spec is not None and language == "python":
            body = []
            for fname, expr in (spec.items() if isinstance(spec, dict) else []):
                if "\n" in str(expr):
                    body.append(str(expr))
                else:
                    body.append("def %s():\n    return %s" % (fname, expr))
            files[fn] = "\n".join(body) if body else "# %s\ndef placeholder():\n    return None\n" % task
        else:
            files[fn] = "# Auto-generated by code-plan for: %s\ndef placeholder():\n    return None\n" % task
        return {"files": files, "score": 70, "source": "generated"}


agent = CodePlanAgent()

if __name__ == "__main__":
    import argparse
    import json
    ap = argparse.ArgumentParser(description="code-plan 原子自测入口")
    ap.add_argument("--capability", default="plan.think", choices=["plan.think", "plan.gen"])
    ap.add_argument("--task", default="实现加法函数 add(a,b)")
    args = ap.parse_args()
    agent.load()
    print("══ code-plan 原子自测 ══", agent.describe()["name"], "status=" + agent.describe()["status"])
    if args.capability == "plan.think":
        r = agent.run(_capability="plan.think", task=args.task)
    else:
        r = agent.run(_capability="plan.gen", task=args.task, spec={"add": "1+1"})
    print(json.dumps(r, ensure_ascii=False, indent=2, default=str))
    if not r["ok"]:
        sys.exit(1)
